import { QlnnModule } from './qlnn/qlnn.module';
import { ReportComponent } from './report.component';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [
  {
    path: '', component: ReportComponent ,children: [
      { path: 'Report008', loadChildren: () => import('./Report008/Report008.module').then(m => m.Report008Module) },
      { path: 'Report010', loadChildren: () => import('./Report010/Report010.module').then(m => m.Report010Module) },
      { path: 'KT11', loadChildren: () => import('./KT11/KT11.module').then(m => m.KT11Module) },
      { path: 'KT12', loadChildren: () => import('./KT12/KT12.module').then(m => m.KT12Module) },
      { path: 'KT13', loadChildren: () => import('./KT13/KT13.module').then(m => m.KT13Module) },
      { path: 'KT14', loadChildren: () => import('./KT14/KT14.module').then(m => m.KT14Module) },
      { path: 'KT22', loadChildren: () => import('./KT22/KT22.module').then(m => m.KT22Module) },
      { path: 'KT25', loadChildren: () => import('./KT25/KT25.module').then(m => m.KT25Module) },
      { path: 'KT25NEW', loadChildren: () => import('./KT25NEW/KT25NEW.module').then(m => m.KT25NEWModule) },
      { path: 'KT26', loadChildren: () => import('./KT26/KT26.module').then(m => m.KT26Module) },
      { path: 'KT27', loadChildren: () => import('./KT27/KT27.module').then(m => m.KT27Module) },
      { path: 'RPMailTripDate', loadChildren: () => import('./RPMailTripDate/RPMailTripDate.module').then(m => m.RPMailTripDateModule) },
      { path: 'RPMailTripMonth', loadChildren: () => import('./RPMailTripMonth/RPMailTripMonth.module').then(m => m.RPMailTripMonthModule) },
      { path: 'RPMailTripSummaryMonth', loadChildren: () => import('./RPMailTripSummaryMonth/RPMailTripSummaryMonth.module').then(m => m.RPMailTripSummaryMonthModule) },
      { path: 'PL05', loadChildren: () => import('./PL05/PL05.module').then(m => m.PL05Module) }, 
      { path: 'PL05_1', loadChildren: () => import('./PL05_1/PL05_1.module').then(m => m.PL05_1Module) }, 
      { path: 'PL05_2', loadChildren: () => import('./PL05_2/PL05_2.module').then(m => m.PL05_2Module) }, 
      { path: 'PL05_3', loadChildren: () => import('./PL05_3/PL05_3.module').then(m => m.PL05_3Module) }, 
      { path: 'PL05_4', loadChildren: () => import('./PL05_4/PL05_4.module').then(m => m.PL05_4Module) }, 
      { path: 'PL05_5', loadChildren: () => import('./PL05_5/PL05_5.module').then(m => m.PL05_5Module) },       
      { path: 'PL05_6', loadChildren: () => import('./PL05_6/PL05_6.module').then(m => m.PL05_6Module) },    
      { path: 'RP001', loadChildren: () => import('./RP001/RP001.module').then(m => m.RP001Module) }, 
      { path: 'RP002', loadChildren: () => import('./RP002/RP002.module').then(m => m.RP002Module) }, 
      { path: 'RP005', loadChildren: () => import('./RP005/RP005.module').then(m => m.RP005Module) }, 
      { path: 'RP006', loadChildren: () => import('./RP006/RP006.module').then(m => m.RP006Module) }, 
      { path: 'KPI_CP16', loadChildren: () => import('./KPI_CP16/KPI_CP16.module').then(m => m.KPI_CP16Module) }, 
      { path: 'KPI_SanLuong', loadChildren: () => import('./KPI_SANLUONG/KPI_SANLUONG.module').then(m => m.KPI_SANLUONGModule) },
      { path: 'KPI_BaoCaoTuan', loadChildren: () => import('./KPI_BaoCaoTuan/KPI_BaoCaoTuan.module').then(m => m.KPI_BaoCaoTuanModule) },
      { path: 'KPI_BaoCaoThang', loadChildren: () => import('./KPI_BaoCaoThang/KPI_BaoCaoThang.module').then(m => m.KPI_BaoCaoThangModule) },
      { path: 'KPI_BaoCaoThang_TongHop', loadChildren: () => import('./KPI_BaoCaoThang_TongHop/KPI_BaoCaoThang_TongHop.module').then(m => m.KPI_BaoCaoThang_TongHopModule) },
      { path: 'KPI_DoiSoat', loadChildren: () => import('./KPI_DoiSoat/KPI_DoiSoat.module').then(m => m.KPI_DoiSoatModule) },
      { path: 'KPI_BangKeChiTietGui', loadChildren: () => import('./KPI_BangKeChiTietGui/KPI_BangKeChiTietGui.module').then(m => m.KPI_BangKeChiTietGuiModule) },
      { path: 'KPI_SanLuong_XN_Thang', loadChildren: () => import('./KPI_SanLuong_XN_Thang/KPI_SanLuong_XN_Thang.module').then(m => m.KPI_SanLuong_XN_ThangModule) },
      { path: 'KPI_BangKeThang_KhachHang', loadChildren: () => import('./KPI_BangKeThang_KhachHang/KPI_BangKeThang_KhachHang.module').then(m => m.KPI_BangKeThang_KhachHangModule) },
      { path: 'KPI_TongHopChiPhi', loadChildren: () => import('./KPI_TongHopChiPhi/KPI_TongHopChiPhi.module').then(m => m.KPI_TongHopChiPhiModule) },
      { path: 'KPI_VNPos_OUT', loadChildren: () => import('./KPI_VNPos_OUT/KPI_VNPos_OUT.module').then(m => m.KPI_VNPos_OUTModule) },
      { path: 'KPI_VNPos_IN', loadChildren: () => import('./KPI_VNPos_IN/KPI_VNPos_IN.module').then(m => m.KPI_VNPos_INModule) },
      { path: 'QLNN', loadChildren: () => import('./qlnn/qlnn.module').then(m => m.QlnnModule) },
      { path: 'KPI_KT1ChTietTheoCa', loadChildren: () => import('./KPI_KT1ChTietTheoCa/KPI_KT1ChTietTheoCa.module').then(m => m.KPI_KT1ChTietTheoCaModule) },
      { path: 'KPI_BcChuyenThuDiNoiTinh', loadChildren: () => import('./KPI_BcChuyenThuDiNoiTinh/KPI_BcChuyenThuDiNoiTinh.module').then(m => m.KPI_BcChuyenThuDiNoiTinhModule) },
      { path: 'QLNN_BCTK1', loadChildren: () => import('./QLNN_BCKT1/QLNN_BCKT1.module').then(m => m.QLNN_BCKT1Module) },
      { path: 'THCLThang', loadChildren: () => import('./THCLThang/THCLThang.module').then(m => m.THCLThangModule) },
      { path: 'KPI_ChamToanTrinhChiTiet', loadChildren: () => import('./KPI_ChamToanTrinhChiTiet/KPI_ChamToanTrinhChiTiet.module').then(m => m.KPI_ChamToanTrinhChiTietModule) },
      { path: 'Chitietsaisot', loadChildren: () => import('./Chitietsaisot/Chitietsaisot.module').then(m => m.ChitietsaisotModule) },
      { path: 'KPI_SL_TongHop', loadChildren: () => import('./KPI_SanLuong_TongHop/KPI_SanLuong_TongHop.module').then(m => m.KPI_SanLuong_TongHopModule) },
      { path: 'PL0708', loadChildren: () => import('./PL0708/PL0708.module').then(m => m.PL0708Module) },
      { path: 'PL0708Month', loadChildren: () => import('./PL0708Month/PL0708Month.module').then(m => m.PL0708MonthModule) },
      { path: 'PL0708StartingCodeMonth', loadChildren: () => import('./PL0708StartingCodeMonth/PL0708StartingCodeMonth.module').then(m => m.PL0708StartingCodeMonthModule) },
      { path: 'KT14_Day', loadChildren: () => import('./KT14_Day/KT14_Day.module').then(m => m.KT14_DayModule) },
      { path: 'KT14_Province', loadChildren: () => import('./KT14_Province/KT14_Province.module').then(m => m.KT14_ProvinceModule) },
      { path: 'KPI_KhaiThacBuuTa', loadChildren: () => import('./KPI_KhaiThacBuuTa/KPI_KhaiThacBuuTa.module').then(m => m.KPI_KhaiThacBuuTaModule) },
      { path: 'KPI_GiaoDichVien', loadChildren: () => import('./KPI_GiaoDichVien/KPI_GiaoDichVien.module').then(m => m.KPI_GiaoDichVienModule) },
      { path: 'KPI_KhaiThacVien', loadChildren: () => import('./KPI_KhaiThacVien/KPI_KhaiThacVien.module').then(m => m.KPI_KhaiThacVienModule) },
      { path: 'KT16', loadChildren: () => import('./KT16/KT16.module').then(m => m.KT16Module) },
      { path: 'KT17', loadChildren: () => import('./KT17/KT17.module').then(m => m.KT17Module) },
      { path: 'TH_KNSV', loadChildren: () => import('./TH_KNSV/TH_KNSV.module').then(m => m.TH_KNSVModule) },
      { path: 'CHITIETVIPHAM', loadChildren: () => import('./CHITIETVIPHAM/CHITIETVIPHAM.module').then(m => m.CHITIETVIPHAMModule) },
      { path: 'KPI_SanLuong_BuuPham_KT1', loadChildren: () => import('./KPI_SanLuong_BuuPham_KT1/KPI_SanLuong_BuuPham_KT1.module').then(m => m.KPI_SanLuong_BuuPham_KT1Module) },
      { path: 'KPI_NangSuat_ChatLuong_GiaoDich', loadChildren: () => import('./KPI_NangSuat_ChatLuong_GiaoDich/KPI_NangSuat_ChatLuong_GiaoDich.module').then(m => m.KPI_NangSuat_ChatLuong_GiaoDichModule) },
      { path: 'KPI_NangSuat_ChatLuong_KhaiThac', loadChildren: () => import('./KPI_NangSuat_ChatLuong_KhaiThac/KPI_NangSuat_ChatLuong_KhaiThac.module').then(m => m.KPI_NangSuat_ChatLuong_KhaiThacModule) },
      { path: 'KPI_NangSuat_ChatLuong_VanChuyen', loadChildren: () => import('./KPI_NangSuat_ChatLuong_VanChuyen/KPI_NangSuat_ChatLuong_VanChuyen.module').then(m => m.KPI_NangSuat_ChatLuong_VanChuyenModule) },
      { path: 'DanhSachPhat', loadChildren: () => import('./DanhSachPhat/DanhSachPhat.module').then(m => m.DanhSachPhatModule) },
      { path: 'KPI_PL0506', loadChildren: () => import('./KPI_PL0506/KPI_PL0506.module').then(m => m.KPI_PL0506Module) },
    ]
  
  },
];

export const ReportRoutes = RouterModule.forChild(routes);
