//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warning
    {
        public long ID { get; set; }
        public string POSCode { get; set; }
        public Nullable<byte> WarningType { get; set; }
        public Nullable<byte> WarningLevel { get; set; }
        public string WarningContent { get; set; }
        public Nullable<long> ExternalID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
