//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');



export class SwaggerResponseHandler<TResult> {
    status: number;
    headers: { [key: string]: any; };
    result: TResult;
    error: any;
    success: boolean;

    constructor(status: number, headers: { [key: string]: any; }, result: TResult) {
        let rs: any = result;
        this.status = status;
        this.headers = headers;
        if (status === 200 || status === 204) {
            this.result = result;
            this.success = true;
        } else {
            this.error = rs?.errors;
            this.success = false;
        }
    }
}